# Pertemuan 3 Data Science 04
## 04 Data Preprocessing dengan Scikit-Learn
## Sumber : https://youtu.be/smNnhEd26Ek

### Sample Data

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1,-1.9,5.5],
                       [-1.5,2.4,3.5],
                       [0.5,-7.9,5.6],
                       [5.9,2.3,-5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [2]:
sample_data.shape

(4, 3)

- teknik data processing.
> data set ini disebut features bila di lihat ada 4 (dilihat dari baris, dari data setnya isinya ada 3.
> cara melihat dimensinya menggunakan `.shape`. jumlah baris ada 4 dan kolomnya ada 3.

### Binarisation

In [3]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [5]:
preprocessor = preprocessing.Binarizer(threshold = 0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

- Binarisation adalah untuk menghasilkan suatu data yang menghasilkan dua numerik saja.
> cara binarisation
> - `preprocessing.Binarizer(threshold = 0.5)` digunakan untuk membuat binarizer dan memerlukan parameter `threshold` yang digunakan untuk melakukan batasan. bila lebih kecil dari threshold maka nilainya menjadi 0 bila lebih besar dari pada thresholdnya maka nilainya menjadi 1.
> - `preprocessor.transform(sample_data)` digunakan untuk transformasi data dan memerlukan parameter `sample_data`

### Scaling

In [6]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [8]:
preprocessor = preprocessing.MinMaxScaler(feature_range =(0,1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [10]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Scaling adalah menghasilkan data numerik pada bentuk skala tertentu.
> cara membuat scaling
> - `preprocessing.MinMaxScaler(feature_range =(0,1))` digunakan untuk mengubah skala terkecil dan terbesar keskala tertentu. dan memerlukan parameter yaitu `(feature_range =(0,1))` yang digunakan untuk memberikan batasan skalanya.  `feature_range` membutuhkan value bentuk data tupple, yang dimana nilai pertama nilai terkecil, dan nilai kedua adalah nilai terbesar
> - `preprocessor.fit(sample_data)` dan memerlukan parameter yaitu `sample_data`
> - proses fitting dan transform dapat disatukan dengan cara `preprocessor.fit_transform(sample_data)`  dan membutuhakan parameter `sample data`

### L1 Normalisation : Least Absolute Deviations

In [11]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [12]:
l1_normalised_data = preprocessing.normalize(sample_data, norm = 'l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

Normalisation least absoulute deviations adalah melakukan normalisasi.
> cara membuatnya
> - `preprocessing.normalize(sample_data, norm = 'l1')` dan membutuhkan dua parameter. parameter pertama yaitu `sample_data`nya dan parameter kedua yaitu `norm = 'l1'` digunakan untuk memberikan style normalisasinya.  value `l1` ini berasosiasi Least Absolute Deviations

### L2 Normalisation : Least Squares

In [13]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [15]:
l2_normalised_data = preprocessing.normalize(sample_data, norm = 'l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

- cara membuatnya sama dengan normalisasi L1, yang membedakan di `norm`, dengan memberikan value `l2`