# Pertemuan 06 Data Science 07
## https://youtu.be/W8adIcfv16M
## Regression Dengan KNN (K Nearest Neighbours)

- KNN adalah model machine learning yang dapat digunakan untuk melakukan prediksi bersadarkan kedekatan karateristik dengan sejulah tetangga terdekat.
- predisi yang diakukan dapat diterapkan baik pada classification maupun regirssion task.

### Sample Dataset

In [1]:
import pandas as pd
sensus = {'tinggi' : [158,170,183,191,155,163,180,158,170],
         'jk':['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'],
         'berat': [64,86,84,80,49,59,67,54,67]}
sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

## Regression (estimasi nilai) dengan KNN

### Features and Target

In [2]:
import numpy as np
X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')


X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


- sebelum membuat training model akan melakukan pengelompokan nilai features dan target.
- kasus kali ini data tinggi dan jenis kelamin akan menjadi features. tinggi dan jenis kelamin akan di bunddle.
- data berat akan menjadi targetnya, 
- disini akan melakukan predisi dari berat badan berdasarkan tinggi badan dan jenis kelamin. karena yang di predisi adalah nilai continues bukan nilai kategori maka kasus ini termasuk pada reggrision task, KKN yang sebelumnya akan mengambil dari tetangga yang terdekat. lalu niali features lebih baik menggunakan nilai numerik

### Preprocess Dataset : Konversi Label menjadi Numerik Biner

In [3]:
X_train_transposed = np.transpose(X_train)
print(f'X_train:\n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transposed}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


- `np.transpose` digunakan untuk mengubah posisi baris menjadi kolom dan posisi kolom menjadi baris. `np.transpose` akan membuat dua bentuk baris.
- tinggi badan menjadi feature pertama dan jenis kelamin menjadi feature kedua.

In [4]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
jk_binarized = lb.fit_transform(X_train_transposed[1])

print(f'jk:{X_train_transposed[1]}')
print(f'jk_binarized:\n{jk_binarized}')

jk:['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']
jk_binarized:
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


- yang di transposed yaitu `X_train_transposed` yang sudah di bagi menjadi dua baris, dan memberikan spesifikasi baris mana yang mau di transform. sebelum di transformasi data yang dilihat hanya menjadi satu dimensi. setelah di tranformasi menjadi dua dimensi.

In [5]:
jk_binarized = jk_binarized.flatten()
jk_binarized 

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

- `flatten` digunakan untuk menggabungkan array multi dimensi menjadi array satu dimensi.

In [6]:
X_train_transposed[1] = jk_binarized 
X_train = X_train_transposed.transpose()

print(f'X_train_transposed:\n{X_train_transposed}\n')
print(f'X_train:\n{X_train}')

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X_train:
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


- nilai yang sudah ditransformasikan akan tampung lagi ke `X_trans_transposed`. 
- `X_train_transposed` akan `ditranspose` lagi supaya dikembalikan kolom menjadi baris dan yang baris menjadi kolom
- pada intinya ingin mengubah nilai jenis kelamin menjadi nilai binary.

In [7]:
X_train_transposed[1] = jk_binarized
X_train = X_train_transposed.transpose()

print(f'X_train_transposed :\n{X_train_transposed}\n')
print(f'X_train:\n{X_train}')

X_train_transposed :
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X_train:
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


### Training KNN Regression Model

In [8]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors = K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

- model meachine learning yang digunakan yaitu KNN, yang berbeda pada `import`nya yaitu `KNeighborsRegressor`,
- K adalah jumlah tetangga yang akan diprediksi

### Prediksi Berat Badan

In [9]:
X_new = np.array([[155,1]])
X_new

array([[155,   1]])

membuat data yang akan dipredisi, isi datanya yaitu tinggi badan dan jenis kelamin

In [10]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

melakukan prediksi, untuk data `155,1` atau tinggi badan 155 dan perempuan dipredisi memiliki berat beadan 55kg.

### Evaluasi KNN Regression Model 

In [11]:
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'X_test:\n{X_test}\n')
print(f'y_test:{y_test}')

X_test:
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test:[65 96 52 67]


menyiapkan 4 data testing set. untuk setiap freature `X_test` dan target `y_test`

In [12]:
y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

lalu melakukan prediksi. namun data (pada `y_test`) yang diharapkan tidak sesuai 

### Coefficient of Determinantion atau $R^2$

In [13]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test, y_pred)
print(f'R-Squared : {r_squared}')

R-Squared : 0.6290565226735438


- untuk melakukan coefficient of determination membutuhkan : `from sklearn.metrics import r2_score`
- untuk membuat `r2_score` memerlukan dua parameter yaitu `y_test` (target), `y_pred` (hasil prediksi)
- nilai R-square bila semakin mendekati 1 maka semakin baik bila mendekati 0 atau negatif maka hasilnya kurang baik.

## Mean Absolut Error (MAE) atau Mean Absolute Deviation (MAD)

$M A E$ is the average of the absolute values of the errors of the predictions.

## $M AE = \frac1n\sum_{i=1}^{n}|y_i - \hat{y}_1| $

- $y_i$ : nilai target
- $\hat{y}_1$ : nilai prediksi



- menghitung selisih atau error untuk $y_i$ dan $\hat{y}_1$
- hasil perhitungan akan memiliki hasil negatif dan positif.
- bila hasil prediksi lebih kecil dari yang seharusnya maka nilainya positif
- bila hasil prediksi lebih besar dari yang seharusnya maka nilainya negatif
- semua nilai negatif akan menjadi positif bila ada method absolut ($| |$)

In [14]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test, y_pred)
print(f'MAE:{MAE}')

MAE:8.333333333333336


bila nilai $M AE$ nya lebih kecil maka hasilnya akan lebih baik.

## Mean Squared Error (MSE) atau MEan Squared Deviation (MSD)

$M SE$ is the average of the squares of the erros of the predictions.

$M SE$ adalah rata rata error kuadrad dari prediksi.



## $M AE = \frac1n\sum_{i=1}^{n}(y_i - \hat{y}_1)^2 $

- $y_i$ : nilai target
- $\hat{y}_1$ : nilai prediksi
- n : jumlah data poin


- menghitung selisih atau error untuk $y_i$ dan $\hat{y}_1$
- hasil perhitungan akan memiliki hasil negatif dan positif.
- bila hasil prediksi lebih kecil dari yang seharusnya maka nilainya positif
- bila hasil prediksi lebih besar dari yang seharusnya maka nilainya negatif
- untuk menghilangkan nilai negatif selisih nilainya akan di pangkat dua, dan akan di akumulasi lalu di bagi dengan n 

In [15]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test, y_pred)
print(f'MSE:{MSE}')

MSE:95.8888888888889


bila nilai $M SE$nya lebih kecil maka modelnya makin baik. nilai $M SE$ akan lebih beasr dari pada $M AE$ 

## Permasalahan Scaling pada Features

In [16]:
from scipy.spatial.distance import euclidean

# tinggi dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
X_new = np.array([[1640,0]])
[euclidean(X_new[0],d) for d in X_train]

[60.0, 40.01249804748511]

terdapat dua nilai features, nilai pertama tinggi badan dalam bentuk milimeter dan jenis kelamin yang bernilai biner 0 untuk pria dan 1 untuk wanita.

menghitung jarak dengan menggunakan `euclidean` distance, yang pertama yaitu jarak dari data poin index 0 dan yang kedua yaitu jarak dari data poin index ke 1.

In [17]:
# tinggi dalam meter
X_train = np.array([[1.7,0],[1.6,1]])
X_new = np.array([[1.64,0]])

[euclidean(X_new[0],d) for d in X_train]

[0.06000000000000005, 1.0007996802557442]

terdapat dua nilai features, nilai pertama tinggi badan dalam bentuk meter dan jenis kelamin yang bernilai biner 0 untuk pria dan 1 untuk wanita.

menghitung jarak dengan menggunakan `euclidean` distance, yang pertama yaitu jarak dari data poin index 0 dan yang kedua yaitu jarak dari data poin index ke 1. bila di lihat terjadi ketidakonsistenan data padahal hanya berbada dalam bentuk pengukuran.

### Menerapkan Standar Scaler (Standar Score atau Z-Score)

Standardize featrues by removing the mean and scaling to unit variance.

## $z = \frac{x - \bar x}S $

- $x$ : nilai feature
- $\bar x$ : rata rata nilai feature
- $S$ : nilai standard deviasi

In [18]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

perlu mengimport StandardScalernya.

In [19]:
# tinggi dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled:\n{X_train_scaled}\n')

X_new = np.array([[1640, 0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled :{X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak: {jarak}')

X_train_scaled:
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled :[[-0.2 -1. ]]

jarak: [1.2, 2.1540659228538015]


terdapat dua nilai features, nilai pertama tinggi badan dalam bentuk milimeter dan jenis kelamin yang bernilai biner 0 untuk pria dan 1 untuk wanita.

setelah nilai Feature di bentuk selanjutnya menggunakan StandardScaler pada X_train. menggunakan `fit_transform`

pada `X_new` tidak melakukan `fit_transform` karena sudah digunakan pada `X_train`, tapi menggunakan `tranform` supaya dapat digunakan pada `X_train` dan `X_new`

lalu menghitung jarak dengan menggunakan `euclidean` distance.

In [20]:
# tinggi dalam meter
X_train = np.array([[1.7,0],[1.6,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled:\n{X_train_scaled}\n')

X_new = np.array([[1.64, 0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled:{X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak : {jarak}')

X_train_scaled:
[[ 1. -1.]
 [-1.  1.]]

X_new_scaled:[[-0.2 -1. ]]

jarak : [1.2000000000000026, 2.1540659228538006]


terdapat dua nilai features, nilai pertama tinggi badan dalam bentuk meter dan jenis kelamin yang bernilai biner 0 untuk pria dan 1 untuk wanita.

setelah nilai Feature di bentuk selanjutnya menggunakan StandardScaler pada X_train. menggunakan `fit_transform`

pada `X_new` tidak melakukan `fit_transform` karena sudah digunakan pada `X_train`, tapi menggunakan `tranform` supaya dapat digunakan pada `X_train` dan `X_new`

lalu menghitung jarak dengan menggunakan `euclidean` distance.

## Menerapkan Features scaling pada KNN

### Dataset

In [21]:
# training set
X_train = np.array([[158,0],[170,0],[183,0],[191,0],[155,1],[163,1],[180,1],[158,1],[170,1]])

y_train = np.array([64,86,84,80,49,59,67,54,67])

# Test Set
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

### Features Scaling (Standard Scaler)

In [25]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

print (f'X_train_scaled:\n{X_train_scaled}\n')
print (f'X_test_scaled :\n{X_test_scaled}\n')

X_train_scaled:
[[-0.9908706  -1.11803399]
 [ 0.01869567 -1.11803399]
 [ 1.11239246 -1.11803399]
 [ 1.78543664 -1.11803399]
 [-1.24326216  0.89442719]
 [-0.57021798  0.89442719]
 [ 0.86000089  0.89442719]
 [-0.9908706   0.89442719]
 [ 0.01869567  0.89442719]]

X_test_scaled :
[[-0.14956537 -1.11803399]
 [ 0.86000089 -1.11803399]
 [-0.82260955  0.89442719]
 [-0.06543485  0.89442719]]



awalnya melakukan scalling terlebih dahulu untuk X_train dan X_testnya.

### Training & Evaluasi model.

In [26]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print(f'MAE : {MAE}')
print(f'MSE : {MSE}')


MAE : 7.583333333333336
MSE : 85.13888888888893


bisa menghasilkan model yang lebih baik dengan menggunakan feature scalling.